# Generated by Django 3.1.3 on 2020-12-01 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20201201_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='masse',
            new_name='massage',
        ),
    ]
